-- return {
--   {
--     "neovim/nvim-lspconfig",
--     opts = {
--       servers = {
--         vtsls = {
--           settings = {
--             typescript = {
--               inlayHints = {
--                 parameterNames = { enabled = "literals" },
--                 parameterTypes = { enabled = true },
--                 variableTypes = { enabled = true },
--                 propertyDeclarationTypes = { enabled = true },
--                 functionLikeReturnTypes = { enabled = true },
--               },
--             },
--           },
--           keys = {
--             {
--               "<leader>co",
--               function()
--                 vim.lsp.buf.code_action({
--                   apply = true,
--                   context = {
--                     only = { "source.organizeImports" },
--                     diagnostics = {},
--                   },
--                 })
--               end,
--               desc = "Organize Imports",
--             },
--             {
--               "<leader>cR",
--               function()
--                 vim.lsp.buf.code_action({
--                   apply = true,
--                   context = {
--                     only = { "source.removeUnused" },
--                     diagnostics = {},
--                   },
--                 })
--               end,
--               desc = "Remove Unused Imports",
--             },
--           },
--         },
--         tailwindcss = {
--           filetypes = {
--             "html",
--             "css",
--             "javascript",
--             "javascriptreact",
--             "typescript",
--             "typescriptreact",
--           },
--         },
--       },
--       setup = {
--         tsserver = function()
--           return false -- ⛔️ Don't use tsserver
--         end,
--         vtsls = function(_, opts)
--           require("lspconfig").vtsls.setup(opts)
--           return true
--         end,
--         tailwindcss = function(_, opts)
--           require("lspconfig").tailwindcss.setup(opts)
--           return true
--         end,
--       },
--     },
--   },
-- }
return {
  -- {
  --   "neovim/nvim-lspconfig",
  --   opts = function(_, opts)
  --     local util = require("lspconfig.util")
  --
  --     opts.servers = opts.servers or {}
  --
  --     -- 🩺 Enhanced diagnostic configuration
  --     opts.diagnostics = {
  --       underline = true,
  --       update_in_insert = false,
  --       virtual_text = {
  --         spacing = 4,
  --         source = "if_many",
  --         prefix = "●",
  --       },
  --       severity_sort = true,
  --       signs = {
  --         text = {
  --           [vim.diagnostic.severity.ERROR] = " ",
  --           [vim.diagnostic.severity.WARN] = " ",
  --           [vim.diagnostic.severity.HINT] = " ",
  --           [vim.diagnostic.severity.INFO] = " ",
  --         },
  --       },
  --     }
  --
  --     -- 🧠 Detect project type
  --     local cwd = vim.fn.getcwd()
  --     local root = util.root_pattern("tsconfig.json", "jsconfig.json", "package.json", ".git")(cwd)
  --     local has_tsconfig = root and vim.fn.filereadable(root .. "/tsconfig.json") == 1
  --
  --     -- 🧩 Tailwind setup
  --     opts.servers.tailwindcss = {
  --       filetypes = {
  --         "html",
  --         "css",
  --         "javascript",
  --         "javascriptreact",
  --         "typescript",
  --         "typescriptreact",
  --       },
  --     }
  --
  --     -- 🟦 TypeScript project → use vtsls
  --     if has_tsconfig then
  --       opts.servers.vtsls = {
  --         settings = {
  --           typescript = {
  --             inlayHints = {
  --               parameterNames = { enabled = "literals" },
  --               parameterTypes = { enabled = true },
  --               variableTypes = { enabled = true },
  --               propertyDeclarationTypes = { enabled = true },
  --               functionLikeReturnTypes = { enabled = true },
  --             },
  --           },
  --         },
  --       }
  --       -- Disable tsserver by setting it to false
  --       opts.servers.tsserver = false
  --     else
  --       -- 🟨 JavaScript project → use tsserver
  --       opts.servers.tsserver = {
  --         settings = {
  --           javascript = {
  --             inlayHints = {
  --               includeInlayParameterNameHints = "all",
  --               includeInlayFunctionParameterTypeHints = true,
  --               includeInlayVariableTypeHints = true,
  --             },
  --           },
  --         },
  --       }
  --       -- Disable vtsls by setting it to false
  --       opts.servers.vtsls = false
  --     end
  --
  --     return opts
  --   end,
  --   keys = {
  --     -- 🧰 Import organization keybindings
  --     {
  --       "<leader>co",
  --       function()
  --         vim.lsp.buf.code_action({
  --           apply = true,
  --           context = {
  --             only = { "source.organizeImports" },
  --             diagnostics = {},
  --           },
  --         })
  --       end,
  --       desc = "Organize Imports",
  --     },
  --     {
  --       "<leader>cR",
  --       function()
  --         vim.lsp.buf.code_action({
  --           apply = true,
  --           context = {
  --             only = { "source.removeUnused" },
  --             diagnostics = {},
  --           },
  --         })
  --       end,
  --       desc = "Remove Unused Imports",
  --     },
  --   },
  -- },
}
